FROM container4armhf/armhf-alpine:3.2

# bootstrap
COPY ./init.sh /init.sh
RUN /init.sh v2

# prepare config and scripts
COPY ./config.yml /etc/devicehive-cloud.yml
COPY ./start.sh /start.sh

ENTRYPOINT ["/start.sh"]
CMD ["--conf", "/etc/devicehive-cloud.yml"]
