FROM container4armhf/armhf-alpine:3.3

# bootstrap
COPY ./init.sh /init.sh
RUN /init.sh --branch=v2 --extra-repo=http://nl.alpinelinux.org/alpine/v3.3/community

# prepare scripts
COPY ./start.sh /start.sh

ENTRYPOINT ["/start.sh"]
