FROM container4armhf/armhf-alpine:3.3

# bootstrap
COPY ./init.sh /init.sh
RUN /init.sh --branch=v2 --extra-repo=http://nl.alpinelinux.org/alpine/v3.3/community

WORKDIR "/go/src/github.com/devicehive/IoT-framework/examples"
ENV GOPATH=/go
CMD ["/bin/sh"]
