FROM container4armhf/armhf-alpine:3.3

# bootstrap
COPY ./init.sh /init.sh
COPY ./*.patch /tmp/
RUN /init.sh --branch=v2 --alljoyn=v15.04 --extra-repo=http://nl.alpinelinux.org/alpine/v3.3/community

# prepare scripts
COPY ./start.sh /start.sh

EXPOSE 9955 9956
ENTRYPOINT ["/start.sh"]
